using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using Sc2Switch2;
class FakePlatform:IPlatform {
    public bool Game,Running,ExitFails,StartFails,WrongRegion,CancelOnStart;
    public int Starts,Exits,Delays;
    public CancellationTokenSource Cancellation;
    public int CancelOnDelay;
    public string Region="EU";
    public bool GameRunning(){return Game;}
    public bool BattleNetRunning(){return Running;}
    public void RequestExit(){Exits++;if(!ExitFails)Running=false;}
    public void StartRegion(string region){Starts++;if(CancelOnStart)Cancellation.Cancel();if(StartFails)throw new IOException("simulated launch failure");Running=true;Region=WrongRegion?"WRONG":region;}
    public string ReadRegion(){return Region;}
    public Task Delay(int ms,CancellationToken token){Delays++;if(Delays==CancelOnDelay)Cancellation.Cancel();token.ThrowIfCancellationRequested();return Task.FromResult(0);}
}
class Tests {
    static int pass;
    static string root,vars,state;
    static Settings settings;
    static string Manifest(string branch,string version,string locale){return "Tags!STRING:0|Version!STRING:0|Extra!STRING:0|Active!DEC:1|Branch!STRING:0\r\nWindows "+locale+" text?:Windows "+locale+" speech?|"+version+"|future|1|"+branch+"\r\n";}
    static void Assert(bool condition,string text){if(!condition)throw new Exception(text);}
    static void Test(string name,Action action){action();pass++;Console.WriteLine("PASS "+name);}
    static void Block(Action action){bool threw=false;try{action();}catch{threw=true;}Assert(threw,"Expected block");}
    static string Placeholders(string value){return String.Join(",",Regex.Matches(value,@"(?<!\{)\{(\d+)(?:,[^}:]+)?(?::[^}]+)?\}(?!\})").Select(m=>m.Groups[1].Value).OrderBy(x=>x));}
    static void Reset(){File.WriteAllText(vars,"account=keep\r\nlocaleidassets=zhCN\r\nlocaleiddata=zhCN\r\nvolume=0.6\r\n",new UTF8Encoding(false));if(File.Exists(Path.Combine(state,"pending-language.json")))File.Delete(Path.Combine(state,"pending-language.json"));}
    static void InitProfile(Profile p,string branch,string locale){Directory.CreateDirectory(p.GamePath);Directory.CreateDirectory(Path.Combine(p.GamePath,"Versions"));File.WriteAllText(Path.Combine(p.GamePath,"StarCraft II.exe"),"");File.WriteAllText(Path.Combine(p.GamePath,".patch.result"),"0");File.WriteAllText(Path.Combine(p.GamePath,".build.info"),Manifest(branch,"9.1.2.123456",locale));}
    static string TestPath(string name){string path=Path.Combine(root,"configuration-store",name);Directory.CreateDirectory(path);return path;}
    static string MutexName(string name)=>"Local\\SC2Switcher-Test-"+name+"-"+Guid.NewGuid().ToString("N");
    static Settings ValidSettings(string folder,string region="EU"){
        string battle=Path.Combine(folder,"Battle.net"),cn=Path.Combine(folder,"China"),global=Path.Combine(folder,"Global"),variables=Path.Combine(folder,"StarCraft II","Variables.txt");
        Directory.CreateDirectory(battle);File.WriteAllText(Path.Combine(battle,"Battle.net.exe"),"");
        var value=new Settings{SchemaVersion=2,BattleNetPath=Path.Combine(battle,"Battle.net.exe"),VariablesPath=variables,GlobalRegion=region,CN=new Profile{Name="国服",GamePath=cn,TextLocale="zhCN",SpeechLocale="zhCN"},Global=new Profile{Name="外服",GamePath=global,TextLocale="enUS",SpeechLocale="enUS"}};
        InitProfile(value.CN,"cn","zhCN");InitProfile(value.Global,"eu","enUS");
        Directory.CreateDirectory(Path.GetDirectoryName(variables));File.WriteAllText(variables,"localeidassets=zhCN\r\nlocaleiddata=zhCN\r\n",new UTF8Encoding(false));
        return value;
    }
    static Settings CopySettings(Settings value)=>ConfigurationValidator.Clone(value);
    static void AssertSettings(Settings actual,Settings expected,string message){Assert(actual.SchemaVersion==expected.SchemaVersion&&actual.GlobalRegion==expected.GlobalRegion&&Paths.Same(actual.BattleNetPath,expected.BattleNetPath)&&Paths.Same(actual.VariablesPath,expected.VariablesPath)&&Paths.Same(actual.CN.GamePath,expected.CN.GamePath)&&Paths.Same(actual.Global.GamePath,expected.Global.GamePath)&&actual.CN.TextLocale==expected.CN.TextLocale&&actual.Global.TextLocale==expected.Global.TextLocale,message);}
    static void BlockField(string field,Action action){try{action();}catch(SettingsValidationException error){Assert(error.Field==field,"Expected "+field+", got "+error.Field);return;}throw new Exception("Expected validation failure for "+field);}
    static ConfigurationStore Store(string stateRoot,string legacyPath=null,string name="store")=>new ConfigurationStore(stateRoot,legacyPath,MutexName(name));
    static int Main(string[] args){try{
        root=Path.GetFullPath(args[0]);Directory.CreateDirectory(root);vars=Path.Combine(root,"Variables.txt");state=Path.Combine(root,"state");
        settings=new Settings{SchemaVersion=2,BattleNetPath=typeof(Tests).Assembly.Location,VariablesPath=vars,GlobalRegion="EU",CN=new Profile{Name="CN",GamePath=Path.Combine(root,"CN"),TextLocale="zhCN",SpeechLocale="zhCN"},Global=new Profile{Name="Global",GamePath=Path.Combine(root,"Global"),TextLocale="enUS",SpeechLocale="enUS"}};
        InitProfile(settings.CN,"cn","zhCN");InitProfile(settings.Global,"kr","enUS");Reset();
        Test("System.Text.Json preserves profiles including Unicode paths",()=>{string f=Path.Combine(root,"profiles.json");Json.Write(f,settings);var s=Settings.Load(f);Assert(s.CN.GamePath==settings.CN.GamePath&&s.GlobalRegion=="EU","Profiles roundtrip");});
        Test("Battle.net region reads unique service values",()=>{Assert(NativePlatform.ParseRegion("{\"Client\":{\"Services\":{\"LastLoginRegion\":\"eu\"}},\"other\":2}")=="EU","Region parse");Assert(NativePlatform.ParseRegion("{\"A\":{\"Services\":{\"LastLoginRegion\":\"EU\"}},\"B\":{\"Services\":{\"LastLoginRegion\":\"CN\"}}}")==null,"Ambiguous region");Assert(NativePlatform.ParseRegion("{\"x\":{\"Services\":5}}") == null,"Invalid service");});
        Test("existing compact language journal remains readable",()=>{string f=Path.Combine(root,"old-journal.json");File.WriteAllText(f,"{\"VariablesPath\":\"D:\\\\Test\\\\Variables.txt\",\"BackupPath\":\"D:\\\\Backups\\\\变量.txt\",\"OriginalHash\":\"ABC\",\"AppliedHash\":\"DEF\",\"Target\":\"Global\",\"Stage\":\"applied\"}");var j=Json.Read<Journal>(f);Assert(j.Stage=="applied"&&j.BackupPath.EndsWith("变量.txt"),"Legacy journal");});
        Test("interface catalogs translate every Chinese key with matching format arguments",()=>{foreach(string key in UiText.Keys){string zh=UiText.Get("zh-CN",key),en=UiText.Get("en-US",key);Assert(zh==key,"Chinese catalog changed key: "+key);Assert(!String.IsNullOrWhiteSpace(en)&&!Regex.IsMatch(en,"[\\u3400-\\u9FFF]"),"English value missing or untranslated: "+key);Assert(Placeholders(zh)==Placeholders(en),"Format arguments differ: "+key);}});
        Test("interface language changes dynamically without touching game language settings",()=>{Reset();string gameHash=Files.HashFile(vars);UiText.SetLanguage("zh-CN");var m=new Sc2Wpf.MainViewModel();m.Initialize("EU","EU");m.Status("正在检查安装","读取两个版本的安装信息。","working");string action=m.ActionLabel,current=m.CurrentRegion,status=m.StatusTitle,step=m.StepLabel;Assert(m.Target=="Global"&&m.Region=="EU","Initial UI model");m.UiLanguage="en-US";Assert(m.UiLanguage=="en-US"&&m.ActionLabel!=action&&m.CurrentRegion!=current&&m.StatusTitle!=status&&m.StepLabel!=step,"UI did not refresh into English");Assert(m.Target=="Global"&&m.Region=="EU"&&Files.HashFile(vars)==gameHash,"UI language changed game selection or locale");m.SetBusy(true);m.UiLanguage="zh-CN";Assert(m.UiLanguage=="en-US","Busy UI language change was allowed");m.SetBusy(false);m.UiLanguage="zh-CN";Assert(m.ActionLabel==action&&m.CurrentRegion==current&&m.StatusTitle==status&&m.StepLabel==step,"UI did not refresh back into Chinese");});
        Test("interface preferences persist separately and invalid files fall back",()=>{Reset();string gameHash=Files.HashFile(vars),prefs=Path.Combine(root,"ui-preferences.json");Assert(UiPreferences.Load(prefs)=="zh-CN","Missing preference did not default to Chinese");File.WriteAllText(prefs,"{ invalid json");Assert(UiPreferences.Load(prefs)=="zh-CN","Invalid preference did not fall back");UiPreferences.Save(prefs,"en-US");Assert(UiPreferences.Load(prefs)=="en-US"&&Files.HashFile(vars)==gameHash,"UI preferences changed game locale");});
        Test("missing directory configuration returns setup defaults without writing beside the executable",()=>{string folder=TestPath("missing");string stateRoot=Path.Combine(folder,"user-state");var store=Store(stateRoot,null,"missing");var loaded=store.Load();Assert(loaded.NeedsSetup&&loaded.Settings.SchemaVersion==2&&!File.Exists(store.ConfigPath),"Missing setup was not represented without a write");Assert(Path.GetDirectoryName(store.ConfigPath).Equals(Path.GetFullPath(stateRoot),StringComparison.OrdinalIgnoreCase),"Configuration was not rooted in the supplied user state");Assert(!Path.GetDirectoryName(store.ConfigPath).Equals(AppContext.BaseDirectory.TrimEnd('\\'),StringComparison.OrdinalIgnoreCase),"Setup selected the executable directory");});
        Test("valid legacy profile migrates into user state and preserves its original bytes",()=>{string folder=TestPath("legacy");var value=ValidSettings(folder);string legacy=Path.Combine(folder,"legacy-profiles.json"),stateRoot=Path.Combine(folder,"user-state");Json.Write(legacy,value);byte[] old=File.ReadAllBytes(legacy);var store=Store(stateRoot,legacy,"legacy");var loaded=store.Load();Assert(loaded.Migrated&&!loaded.NeedsSetup&&File.Exists(store.ConfigPath),"Legacy profile did not migrate");Assert(File.ReadAllBytes(legacy).SequenceEqual(old),"Legacy profile was overwritten");AssertSettings(loaded.Settings,value,"Migrated settings changed");});
        Test("user configuration wins over a legacy profile",()=>{string folder=TestPath("user-priority");var legacyValue=ValidSettings(Path.Combine(folder,"legacy"),"EU");var userValue=ValidSettings(Path.Combine(folder,"user"),"US");string legacy=Path.Combine(folder,"legacy.json"),stateRoot=Path.Combine(folder,"user-state");Json.Write(legacy,legacyValue);Directory.CreateDirectory(stateRoot);Json.Write(Path.Combine(stateRoot,"profiles.json"),userValue);var loaded=Store(stateRoot,legacy,"priority").Load();Assert(!loaded.Migrated&&!loaded.NeedsSetup,"Existing user configuration migrated unexpectedly");AssertSettings(loaded.Settings,userValue,"Legacy configuration overrode user configuration");});
        Test("directory selector rejects relative roots and network locations",()=>{string folder=TestPath("selector");var value=ValidSettings(folder);BlockField("BattleNetDirectory",()=>ConfigurationValidator.FromDirectories(value,"Battle.net",value.CN.GamePath,value.Global.GamePath,value.VariablesPath));BlockField("GlobalDirectory",()=>ConfigurationValidator.FromDirectories(value,value.BattleNetPath,value.CN.GamePath,Path.GetPathRoot(folder),value.VariablesPath));BlockField("GlobalDirectory",()=>ConfigurationValidator.FromDirectories(value,value.BattleNetPath,value.CN.GamePath,"\\\\server\\share\\SC2",value.VariablesPath));});
        Test("directory selector builds a valid configuration from the four selected locations",()=>{string folder=TestPath("selector-valid");var value=ValidSettings(folder,"KR");var selected=ConfigurationValidator.FromDirectories(value,Path.GetDirectoryName(value.BattleNetPath),value.CN.GamePath,value.Global.GamePath,value.VariablesPath);Assert(Paths.Same(selected.BattleNetPath,value.BattleNetPath)&&selected.GlobalRegion=="KR","Selected Battle.net directory was not normalized to its executable");AssertSettings(ConfigurationValidator.Validate(selected),value,"Selected directory configuration did not validate");});
        Test("validation rejects identical or nested game installations",()=>{string folder=TestPath("overlap");var value=ValidSettings(folder);var same=CopySettings(value);same.Global.GamePath=same.CN.GamePath;BlockField("GlobalDirectory",()=>ConfigurationValidator.Validate(same));var nested=CopySettings(value);nested.Global.GamePath=Path.Combine(nested.CN.GamePath,"Nested");Directory.CreateDirectory(nested.Global.GamePath);BlockField("GlobalDirectory",()=>ConfigurationValidator.Validate(nested));});
        Test("validation detects swapped installations and language or launcher errors",()=>{string folder=TestPath("mismatch");var value=ValidSettings(folder);var swapped=CopySettings(value);string originalCn=swapped.CN.GamePath;swapped.CN.GamePath=swapped.Global.GamePath;swapped.Global.GamePath=originalCn;BlockField("ChinaDirectory",()=>ConfigurationValidator.Validate(swapped));var globalCn=CopySettings(value);globalCn.Global.GamePath=Path.Combine(folder,"SecondCN");InitProfile(globalCn.Global,"cn","zhCN");BlockField("GlobalDirectory",()=>ConfigurationValidator.Validate(globalCn));var language=CopySettings(value);language.Global.TextLocale="zhCN";language.Global.SpeechLocale="zhCN";BlockField("GlobalDirectory",()=>ConfigurationValidator.Validate(language));File.Delete(value.BattleNetPath);BlockField("BattleNetDirectory",()=>ConfigurationValidator.Validate(value));});
        Test("validation rejects missing or ambiguous Variables files",()=>{string folder=TestPath("variables");var value=ValidSettings(folder);File.Delete(value.VariablesPath);BlockField("VariablesFile",()=>ConfigurationValidator.Validate(value));File.WriteAllText(value.VariablesPath,"localeidassets=zhCN\r\nlocaleiddata=zhCN\r\nlocaleiddata=zhCN\r\n");BlockField("VariablesFile",()=>ConfigurationValidator.Validate(value));});
        Test("invalid saves preserve the existing config and never change fixture game settings",()=>{string folder=TestPath("invalid-save");var value=ValidSettings(folder);string stateRoot=Path.Combine(folder,"user-state");var initial=Store(stateRoot,null,"invalid-initial");initial.Load();initial.Save(value);byte[] config=File.ReadAllBytes(initial.ConfigPath),variables=File.ReadAllBytes(value.VariablesPath);var writer=Store(stateRoot,null,"invalid-writer");writer.Load();var invalid=CopySettings(value);invalid.Global.GamePath=invalid.CN.GamePath;BlockField("GlobalDirectory",()=>writer.Save(invalid));Assert(File.ReadAllBytes(initial.ConfigPath).SequenceEqual(config),"Invalid save changed valid configuration");Assert(File.ReadAllBytes(value.VariablesPath).SequenceEqual(variables),"Validation changed game Variables.txt");});
        Test("valid save survives a restart and creates a backup before replacement",()=>{string folder=TestPath("persist");var value=ValidSettings(folder);string stateRoot=Path.Combine(folder,"user-state");var store=Store(stateRoot,null,"persist-a");store.Load();store.Save(value);var changed=CopySettings(value);changed.GlobalRegion="US";store.Save(changed);string backups=Path.Combine(stateRoot,"ConfigurationBackups");Assert(Directory.Exists(backups)&&Directory.GetFiles(backups,"*.json").Length==1,"Configuration replacement was not backed up");var reopened=Store(stateRoot,null,"persist-b").Load();Assert(!reopened.NeedsSetup&&!reopened.Migrated,"Restart did not load saved configuration");AssertSettings(reopened.Settings,changed,"Restart settings differ from saved configuration");});
        Test("corrupt user JSON falls back to setup and is backed up before a valid replacement",()=>{string folder=TestPath("corrupt");var value=ValidSettings(folder);string stateRoot=Path.Combine(folder,"user-state");Directory.CreateDirectory(stateRoot);string path=Path.Combine(stateRoot,"profiles.json");byte[] broken=Encoding.UTF8.GetBytes("{ badly broken json");File.WriteAllBytes(path,broken);var store=Store(stateRoot,null,"corrupt");var loaded=store.Load();Assert(loaded.NeedsSetup&&File.ReadAllBytes(path).SequenceEqual(broken),"Corrupt configuration was not safely retained at load");store.Save(value);string backup=Directory.GetFiles(Path.Combine(stateRoot,"ConfigurationBackups"),"*.json").Single();Assert(File.ReadAllBytes(backup).SequenceEqual(broken),"Corrupt configuration bytes were not backed up");AssertSettings(Store(stateRoot,null,"corrupt-restart").Load().Settings,value,"Valid replacement was not readable");});
        Test("a structurally valid user JSON with a missing installation returns setup while retaining paths and bytes",()=>{string folder=TestPath("stale-user-json");var value=ValidSettings(folder);string stateRoot=Path.Combine(folder,"user-state");Directory.CreateDirectory(stateRoot);string path=Path.Combine(stateRoot,"profiles.json");Json.Write(path,value);byte[] original=File.ReadAllBytes(path);File.Delete(value.BattleNetPath);var loaded=Store(stateRoot,null,"stale-user").Load();Assert(loaded.NeedsSetup,"Invalid saved installation was accepted as ready");Assert(Paths.Same(loaded.Settings.BattleNetPath,value.BattleNetPath)&&Paths.Same(loaded.Settings.CN.GamePath,value.CN.GamePath),"Invalid saved paths were discarded instead of being available for correction");Assert(File.ReadAllBytes(path).SequenceEqual(original),"Failed validation changed the saved JSON");});
        Test("unsupported or incomplete saved JSON returns setup without changing its bytes",()=>{string folder=TestPath("unsupported-json");var value=ValidSettings(folder);string stateRoot=Path.Combine(folder,"user-state");Directory.CreateDirectory(stateRoot);string path=Path.Combine(stateRoot,"profiles.json");var future=CopySettings(value);future.SchemaVersion=3;Json.Write(path,future);byte[] futureBytes=File.ReadAllBytes(path);Assert(Store(stateRoot,null,"future-schema").Load().NeedsSetup,"Unsupported schema was accepted as ready");Assert(File.ReadAllBytes(path).SequenceEqual(futureBytes),"Unsupported schema JSON was changed at load");var incomplete=CopySettings(value);incomplete.CN=null;Json.Write(path,incomplete);byte[] incompleteBytes=File.ReadAllBytes(path);Assert(Store(stateRoot,null,"missing-profile").Load().NeedsSetup,"Missing profile was accepted as ready");Assert(File.ReadAllBytes(path).SequenceEqual(incompleteBytes),"Incomplete JSON was changed at load");});
        Test("two windows cannot overwrite a configuration changed after their load",()=>{string folder=TestPath("concurrency");var value=ValidSettings(folder);string stateRoot=Path.Combine(folder,"user-state");var seed=Store(stateRoot,null,"concurrency-seed");seed.Load();seed.Save(value);var first=Store(stateRoot,null,"concurrency-first");var second=Store(stateRoot,null,"concurrency-second");first.Load();second.Load();var update=CopySettings(value);update.GlobalRegion="US";first.Save(update);var stale=CopySettings(value);stale.GlobalRegion="KR";Block(()=>second.Save(stale));AssertSettings(Store(stateRoot,null,"concurrency-final").Load().Settings,update,"Stale window overwrote a newer configuration");});
        Test("pending recovery blocks path changes but permits a region-only update",()=>{string folder=TestPath("pending");var value=ValidSettings(folder);string stateRoot=Path.Combine(folder,"user-state");var seed=Store(stateRoot,null,"pending-seed");seed.Load();seed.Save(value);File.WriteAllText(Path.Combine(stateRoot,"pending-language.json"),"{}");var writer=Store(stateRoot,null,"pending-writer");writer.Load();var regionOnly=CopySettings(value);regionOnly.GlobalRegion="US";writer.Save(regionOnly);var pathChange=CopySettings(regionOnly);pathChange.Global.GamePath=Path.Combine(folder,"OtherGlobal");InitProfile(pathChange.Global,"eu","enUS");Block(()=>writer.Save(pathChange));AssertSettings(Store(stateRoot,null,"pending-final").Load().Settings,regionOnly,"Pending recovery accepted an installation path change");});
        Test("write-time access failures leave existing configuration bytes intact",()=>{string folder=TestPath("write-failure");var value=ValidSettings(folder);string stateRoot=Path.Combine(folder,"user-state");var seed=Store(stateRoot,null,"failure-seed");seed.Load();seed.Save(value);var writer=Store(stateRoot,null,"failure-writer");writer.Load();byte[] before=File.ReadAllBytes(writer.ConfigPath);using(var held=new FileStream(writer.ConfigPath,FileMode.Open,FileAccess.Read,FileShare.None)){var changed=CopySettings(value);changed.GlobalRegion="US";Block(()=>writer.Save(changed));}Assert(File.ReadAllBytes(writer.ConfigPath).SequenceEqual(before),"Failed write changed the existing configuration");});
        Test("future build and reordered named columns",()=>Assert(BuildInfo.Load(settings.Global,false).Version=="9.1.2.123456","Version dependency"));
        Test("missing or duplicate manifest fields rejected",()=>{Block(()=>BuildInfo.Parse("Active|Version\n1|1.2.3.4"));Block(()=>BuildInfo.Parse("Branch|Active|Version|Tags|Tags\ncn|1|1.2.3.4|x|x"));});
        Test("ambiguous active build rejected",()=>Block(()=>BuildInfo.Parse(Manifest("cn","1.2.3.4","zhCN")+"Windows zhCN text?:Windows zhCN speech?|1.2.3.5|future|1|cn\r\n")));
        Test("separate paths required",()=>{Block(()=>Paths.RequireSeparate(root,root+"\\sub"));Block(()=>Paths.RequireSeparate(root,root.ToUpperInvariant()));});
        Test("wrong branch blocked",()=>Block(()=>BuildInfo.Load(settings.Global,true)));
        Test("uninstalled language blocked",()=>{var copy=new Profile{Name="X",GamePath=settings.Global.GamePath,TextLocale="zhCN",SpeechLocale="zhCN"};Block(()=>BuildInfo.Load(copy,false));});
        Test("missing completion marker blocked",()=>{string path=Path.Combine(settings.Global.GamePath,".patch.result");File.Move(path,path+".bak");Block(()=>BuildInfo.Load(settings.Global,false));File.Move(path+".bak",path);});
        Test("failed completion marker blocked",()=>{string path=Path.Combine(settings.Global.GamePath,".patch.result");File.WriteAllText(path,"1");Block(()=>BuildInfo.Load(settings.Global,false));File.WriteAllText(path,"0");});
        Test("language preserves other bytes and roundtrip",()=>{byte[] old=File.ReadAllBytes(vars);byte[] en=Language.Change(old,"enUS","enUS");Assert(Language.Change(en,"zhCN","zhCN").SequenceEqual(old),"Roundtrip mismatch");Assert(Language.Change(en,"enUS","enUS").SequenceEqual(en),"Idempotence");});
        Test("encoding and line endings retained",()=>{var enc=new UnicodeEncoding(true,true,true);byte[] old=enc.GetPreamble().Concat(enc.GetBytes(File.ReadAllText(vars))).ToArray();Assert(Language.Change(Language.Change(old,"enUS","enUS"),"zhCN","zhCN").SequenceEqual(old),"UTF16BE");});
        Test("missing or duplicate language key blocks",()=>{Block(()=>Language.Change(Encoding.UTF8.GetBytes("localeiddata=zhCN\n"),"enUS","enUS"));Block(()=>Language.Change(Encoding.UTF8.GetBytes(File.ReadAllText(vars)+"localeiddata=zhCN\n"),"enUS","enUS"));});
        Test("live writer activity detected",()=>{using(var g=new ActivityGuard(new[]{settings.Global.GamePath})){File.WriteAllText(Path.Combine(settings.Global.GamePath,"update.tmp"),"updating");Thread.Sleep(150);Block(()=>g.Check());}});
        Test("game running prevents writes and launches",()=>{Reset();string hash=Files.HashFile(vars);var p=new FakePlatform{Game=true};Block(()=>new Engine(settings,state,p).Switch("Global",s=>{},CancellationToken.None).GetAwaiter().GetResult());Assert(p.Starts==0&&Files.HashFile(vars)==hash,"Unsafe change");});
        Test("shutdown timeout prevents language mutation",()=>{Reset();string hash=Files.HashFile(vars);var p=new FakePlatform{Running=true,ExitFails=true};Block(()=>new Engine(settings,state,p).Switch("Global",s=>{},CancellationToken.None).GetAwaiter().GetResult());Assert(p.Starts==0&&Files.HashFile(vars)==hash,"Unsafe timeout");});
        Test("launch failure restores original",()=>{Reset();string hash=Files.HashFile(vars);var p=new FakePlatform{StartFails=true};Block(()=>new Engine(settings,state,p).Switch("Global",s=>{},CancellationToken.None).GetAwaiter().GetResult());Assert(Files.HashFile(vars)==hash&&!File.Exists(Path.Combine(state,"pending-language.json")),"Rollback failed");});
        Test("region verification failure restores original",()=>{Reset();string hash=Files.HashFile(vars);var p=new FakePlatform{WrongRegion=true};Block(()=>new Engine(settings,state,p).Switch("Global",s=>{},CancellationToken.None).GetAwaiter().GetResult());Assert(Files.HashFile(vars)==hash,"Region rollback failed");});
        Test("crash journal recovered on next start",()=>{Reset();string hash=Files.HashFile(vars);var tx=new LanguageTransaction(state,vars);tx.Apply("Global",settings.Global,()=>{});Assert(File.Exists(Path.Combine(state,"pending-language.json")),"Journal missing");LanguageTransaction.Recover(state,vars,()=>{});Assert(Files.HashFile(vars)==hash,"Recovery failed");});
        Test("recovery refuses externally changed settings",()=>{Reset();var tx=new LanguageTransaction(state,vars);tx.Apply("Global",settings.Global,()=>{});File.AppendAllText(vars,"new-setting=keep\n");string hash=Files.HashFile(vars);Block(()=>LanguageTransaction.Recover(state,vars,()=>{}));Assert(Files.HashFile(vars)==hash,"New settings overwritten");Reset();});
        Test("successful switch commits and backs up",()=>{Reset();var p=new FakePlatform{Running=true};var r=new Engine(settings,state,p).Switch("Global",s=>{},CancellationToken.None).GetAwaiter().GetResult();Assert(p.Exits==1&&p.Starts==1&&r.Region=="EU"&&File.Exists(r.Backup)&&!File.Exists(Path.Combine(state,"pending-language.json")),"Commit failed");});
        Test("missing target install fails closed",()=>{string path=Path.Combine(settings.Global.GamePath,".build.info");File.Move(path,path+".bak");var p=new FakePlatform();Block(()=>new Engine(settings,state,p).Switch("Global",s=>{},CancellationToken.None).GetAwaiter().GetResult());Assert(p.Starts==0,"Missing install ignored");File.Move(path+".bak",path);});
        Test("already cancelled switch neither recovers nor launches",()=>{Reset();var tx=new LanguageTransaction(state,vars);tx.Apply("Global",settings.Global,()=>{});string applied=Files.HashFile(vars);using(var c=new CancellationTokenSource()){c.Cancel();var p=new FakePlatform();Block(()=>new Engine(settings,state,p).Switch("Global",s=>{},c.Token).GetAwaiter().GetResult());Assert(p.Starts==0&&Files.HashFile(vars)==applied&&File.Exists(Path.Combine(state,"pending-language.json")),"Cancelled start changed existing journal");}Reset();});
        Test("cancel before exit leaves language unchanged",()=>{Reset();string hash=Files.HashFile(vars);using(var c=new CancellationTokenSource()){var p=new FakePlatform{Cancellation=c,CancelOnDelay=1};Block(()=>new Engine(settings,state,p).Switch("Global",s=>{},c.Token).GetAwaiter().GetResult());Assert(p.Starts==0&&Files.HashFile(vars)==hash,"Early cancellation");}});
        Test("cancel at final pre-launch boundary restores language without launch",()=>{Reset();string hash=Files.HashFile(vars);using(var c=new CancellationTokenSource()){var p=new FakePlatform();Block(()=>new Engine(settings,state,p).Switch("Global",s=>{},c.Token,phase=>{if(phase==SwitchPhase.StartingBattleNet)c.Cancel();}).GetAwaiter().GetResult());Assert(p.Starts==0&&Files.HashFile(vars)==hash&&!File.Exists(Path.Combine(state,"pending-language.json")),"Late pre-launch cancellation did not roll back");}});
        Test("cancel in region launch still commits target language and region",()=>{Reset();string hash=Files.HashFile(vars);using(var c=new CancellationTokenSource()){var p=new FakePlatform{Cancellation=c,CancelOnStart=true};var r=new Engine(settings,state,p).Switch("Global",s=>{},c.Token).GetAwaiter().GetResult();Assert(c.IsCancellationRequested&&p.Starts==1&&r.Region=="EU"&&Files.HashFile(vars)!=hash&&!File.Exists(Path.Combine(state,"pending-language.json")),"Irrevocable launch was rolled back or left journal");}});
        Test("cancel during region confirmation still commits target language and region",()=>{Reset();string hash=Files.HashFile(vars);using(var c=new CancellationTokenSource()){var p=new FakePlatform{Cancellation=c,CancelOnDelay=3};var r=new Engine(settings,state,p).Switch("Global",s=>{},c.Token).GetAwaiter().GetResult();Assert(c.IsCancellationRequested&&p.Starts==1&&r.Region=="EU"&&Files.HashFile(vars)!=hash&&!File.Exists(Path.Combine(state,"pending-language.json")),"Confirmation cancellation caused rollback or stranded journal");}});
        Test("UI busy state locks target, region, and interface language",()=>{UiText.SetLanguage("zh-CN");var m=new Sc2Wpf.MainViewModel();m.Initialize("EU","EU");m.SetReady(true);Assert(m.IsGlobal&&m.CanSwitch&&m.CanEditRegion,"Initial state");m.IsChina=true;Assert(!m.CanEditRegion&&m.ActionLabel=="切换到国服","CN state");m.SetBusy(true);m.IsGlobal=true;m.Asia=true;m.UiLanguage="en-US";Assert(m.IsChina&&m.Region=="EU"&&m.UiLanguage=="zh-CN"&&!m.CanSwitch&&!m.CanEditRegion&&m.BusyVisibility==System.Windows.Visibility.Visible&&m.BusyLabel=="正在切换","Busy state allowed a mutable selection or language");m.SetBusy(false);Assert(m.IsIdle&&m.CanSwitch&&m.BusyVisibility==System.Windows.Visibility.Collapsed,"Busy exit did not restore interaction");});
        Test("UI phase advances through non-cancellable busy completion",()=>{UiText.SetLanguage("zh-CN");var m=new Sc2Wpf.MainViewModel();m.SetReady(true);m.SetBusy(true);m.SetPhase(SwitchPhase.Checking);Assert(!m.IsCommitStarted&&m.StepLabel=="阶段 1 / 3"&&m.BusyVisibility==System.Windows.Visibility.Visible,"Checking phase state");m.SetPhase(SwitchPhase.StartingBattleNet);Assert(m.IsCommitStarted&&m.StepLabel=="阶段 3 / 3"&&m.BusyLabel=="正在切换","Launch phase did not show busy completion");m.SetBusy(false);Assert(!m.IsCommitStarted&&m.IsIdle&&m.CanSwitch&&m.BusyVisibility==System.Windows.Visibility.Collapsed,"Completion did not restore interaction");});
        Test("selecting a target does not change current region",()=>{var m=new Sc2Wpf.MainViewModel();m.Initialize("EU","EU");m.IsChina=true;Assert(m.Target=="CN"&&m.CurrentRegion=="外服 · 欧洲","Selection mistaken for current state");m.IsGlobal=true;m.Asia=true;Assert(m.CurrentRegion=="外服 · 欧洲"&&m.Region=="KR","Region preference mistaken for current state");});
        Test("inspection blocks competing actions until complete",()=>{var m=new Sc2Wpf.MainViewModel();m.SetReady(true);m.SetInspecting(true);Assert(!m.CanInspect&&!m.CanSwitch,"Concurrent action allowed");m.SetInspecting(false);Assert(m.CanInspect&&m.CanSwitch,"Controls stay locked");});
        Test("progress and error actions appear in matching states",()=>{var m=new Sc2Wpf.MainViewModel();m.SetBusy(true);m.SetStage(2);Assert(m.ProgressVisibility==System.Windows.Visibility.Visible&&m.StepLabel=="阶段 2 / 3","Progress stage");m.SetBusy(false);m.Status("Failed","Long failure detail","error");Assert(m.ProgressVisibility==System.Windows.Visibility.Collapsed&&m.ErrorVisibility==System.Windows.Visibility.Visible,"Error action missing");m.Status("Ready","Complete");Assert(m.ErrorVisibility==System.Windows.Visibility.Collapsed,"Stale error action");});
        Console.WriteLine("TOTAL "+pass+" PASSED");
        return 0;
    }catch(Exception error){Console.Error.WriteLine("FAIL "+error);return 1;}}
}
