[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$CandidateMsi,
    [string]$OutputDirectory,
    [switch]$ChildMode,
    [string]$WorkDirectory,
    [string]$ParentSid,
    [string]$BaselineFixture,
    [string]$CandidateFixture
)

$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$root=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))
$artifactsRoot=[IO.Path]::GetFullPath((Join-Path $root 'artifacts'))
$runtime=@('SC2Switcher.Wpf.exe','SC2Switcher.Wpf.dll','SC2Switcher.Wpf.deps.json','SC2Switcher.Wpf.runtimeconfig.json')

function Stable-Guid([string]$text){$sha=[Security.Cryptography.SHA256]::Create();try{$b=$sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($text))}finally{$sha.Dispose()};'{'+([guid]::new([byte[]]$b[0..15])).ToString().ToUpperInvariant()+'}'}
function Open-Msi([string]$path,[int]$mode=0){$i=New-Object -ComObject WindowsInstaller.Installer;$d=$i.OpenDatabase($path,$mode);[pscustomobject]@{Installer=$i;Database=$d}}
function Sql($db,[string]$sql,[object[]]$values=@()){$v=$db.OpenView($sql);$i=$null;$r=$null;try{if(!$values.Count){[void]$v.Execute();return};$i=New-Object -ComObject WindowsInstaller.Installer;$r=$i.CreateRecord($values.Count);for($n=0;$n-lt$values.Count;$n++){if($values[$n]-is[int]){$null=($r.IntegerData($n+1)=$values[$n])}elseif($null-ne$values[$n]){$null=($r.StringData($n+1)=[string]$values[$n])}};[void]$v.Execute($r)}finally{[void]$v.Close();foreach($o in @($r,$i,$v)){if($null-ne$o-and[Runtime.InteropServices.Marshal]::IsComObject($o)){[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($o)}}}}
function Set-Value($db,[string]$table,[string]$column,[string]$keyColumn,[string]$key,[string]$value){Sql $db ("UPDATE ``$table`` SET ``$column``=? WHERE ``$keyColumn``=?") @($value,$key)}
function Set-UpgradeCode($db,[string]$code){$v=$db.OpenView('SELECT * FROM `Upgrade`');try{[void]$v.Execute();while($r=$v.Fetch()){try{[void]$v.Modify(6,$r);$null=($r.StringData(1)=$code);[void]$v.Modify(1,$r)}finally{[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($r)}}}finally{[void]$v.Close();[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($v)}}
function Msi-Map([string]$path,[string]$query){$o=Open-Msi $path;$m=@{};$v=$o.Database.OpenView($query);try{[void]$v.Execute();while($r=$v.Fetch()){try{$m[[string]$r.StringData(1)]=[string]$r.StringData(2)}finally{[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($r)}}}finally{[void]$v.Close();[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($v);[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($o.Database);[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($o.Installer)};$m}
function Msi-PackageCode([string]$path){$o=Open-Msi $path;try{$s=$o.Database.SummaryInformation(0);try{[string]$s.Property(9)}finally{[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($s)}}finally{[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($o.Database);[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($o.Installer)}}
function New-Fixture([string]$source,[string]$destination,[string]$role,[string]$version,[string]$token){Copy-Item $source $destination;$o=Open-Msi $destination 1;try{$pc=Stable-Guid "$token/product/$role";$uc=Stable-Guid "$token/upgrade";$package=Stable-Guid "$token/package/$role";foreach($x in @(@('ProductCode',$pc),@('ProductVersion',$version),@('ProductName',"SC2 CI Rollback QA $token"),@('Manufacturer','SC2 CI Rollback QA'),@('UpgradeCode',$uc))){Set-Value $o.Database Property Value Property $x[0] $x[1]};Set-UpgradeCode $o.Database $uc;Set-Value $o.Database Directory DefaultDir Directory ProductRoot "SC2CIQA|SC2CiRollbackQA$token";Set-Value $o.Database Directory DefaultDir Directory MenuGroup "SC2CIQA|SC2 CI Rollback QA $token";Set-Value $o.Database Directory DefaultDir Directory INSTALLDIR $(if($role-eq'baseline'){'old'}else{'app'});Set-Value $o.Database Shortcut Name Shortcut StartMenu "SC2CIQA|SC2 CI Rollback QA $token";Set-Value $o.Database Registry Key Registry AppPath "Software\Microsoft\Windows\CurrentVersion\App Paths\SC2CiRollbackQA.$token.exe";Set-Value $o.Database Registry Key Registry MenuMarker "Software\SC2CiRollbackQA\$token\Installer";Set-Value $o.Database Registry Key Registry ApplicationMarker "Software\SC2CiRollbackQA\$token\Installer";foreach($c in @('Application','StartMenu','AppRegistration')){Set-Value $o.Database Component ComponentId Component $c (Stable-Guid "$token/component/$role/$c")};$s=$o.Database.SummaryInformation(20);try{$null=($s.Property(3)="SC2 CI Rollback QA $token");$null=($s.Property(9)=$package);[void]$s.Persist()}finally{[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($s)};[void]$o.Database.Commit();[pscustomobject]@{Role=$role;Path=$destination;ProductCode=$pc;UpgradeCode=$uc;PackageCode=$package;SHA256=$null}}finally{[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($o.Database);[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($o.Installer);[GC]::Collect();[GC]::WaitForPendingFinalizers()}}
function Verify-Fixture($fixture,[string]$token){$p=Msi-Map $fixture.Path 'SELECT `Property`,`Value` FROM `Property`';$d=Msi-Map $fixture.Path 'SELECT `Directory`,`DefaultDir` FROM `Directory`';$r=Msi-Map $fixture.Path 'SELECT `Registry`,`Key` FROM `Registry`';$u=Msi-Map $fixture.Path 'SELECT `ActionProperty`,`UpgradeCode` FROM `Upgrade`';$s=Msi-Map $fixture.Path 'SELECT `Shortcut`,`Name` FROM `Shortcut`';$c=Msi-Map $fixture.Path 'SELECT `Component`,`ComponentId` FROM `Component`';$expectedInstall=if($fixture.Role-eq'baseline'){'old'}else{'app'};$qaMarker="Software\SC2CiRollbackQA\$token\Installer";$qaAppPath="Software\Microsoft\Windows\CurrentVersion\App Paths\SC2CiRollbackQA.$token.exe";if($p.ProductCode-ne$fixture.ProductCode-or$p.UpgradeCode-ne$fixture.UpgradeCode-or$p.ProductName-ne"SC2 CI Rollback QA $token"-or(Msi-PackageCode $fixture.Path)-ne$fixture.PackageCode-or$d.ProductRoot-ne"SC2CIQA|SC2CiRollbackQA$token"-or$d.MenuGroup-ne"SC2CIQA|SC2 CI Rollback QA $token"-or$d.INSTALLDIR-ne$expectedInstall-or$r.Count-ne3-or$r.AppPath-ne$qaAppPath-or$r.MenuMarker-ne$qaMarker-or$r.ApplicationMarker-ne$qaMarker-or$u.Count-ne2-or@($u.Values|Where-Object{$_-ne$fixture.UpgradeCode}).Count-or$s.StartMenu-ne"SC2CIQA|SC2 CI Rollback QA $token"){throw "Fixture resource remap verification failed: $($fixture.Role)"};foreach($name in @('Application','StartMenu','AppRegistration')){if($c[$name]-ne(Stable-Guid "$token/component/$($fixture.Role)/$name")){throw "Fixture component remap failed: $($fixture.Role)/$name"}}}
function Product-State([string]$code){$i=New-Object -ComObject WindowsInstaller.Installer;try{[int]$i.ProductState($code)}finally{[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($i)}}
function Run-Msi([string]$label,[string[]]$arguments,[int[]]$expected,[string]$logDir,[Collections.Generic.List[object]]$steps){$log=Join-Path $logDir "$label.log";$quoted=@($arguments|ForEach-Object{if($_-match'\s'){'"'+$_.Replace('"','\"')+'"'}else{$_}})+@('/qn','/norestart','REBOOT=ReallySuppress','/L*v',('"'+$log.Replace('"','\"')+'"'));$p=Start-Process (Join-Path $env:WINDIR 'System32\msiexec.exe') -ArgumentList $quoted -WindowStyle Hidden -Wait -PassThru;$code=[uint32]$p.ExitCode;$steps.Add([pscustomobject]@{Step=$label;ExitCode=$code;Expected=$expected-contains$code;Log=$log});if($code-notin$expected){throw "$label returned $code"};$code}
function File-Hashes([string]$dir){$m=[ordered]@{};foreach($n in $runtime){$p=Join-Path $dir $n;$m[$n]=if(Test-Path $p -PathType Leaf){(Get-FileHash $p -Algorithm SHA256).Hash}else{$null}};$m}
function Reg-Default([string]$sub){$b=[Microsoft.Win32.RegistryKey]::OpenBaseKey([Microsoft.Win32.RegistryHive]::CurrentUser,[Microsoft.Win32.RegistryView]::Registry64);try{$k=$b.OpenSubKey($sub);if(!$k){return $null};try{[string]$k.GetValue($null)}finally{$k.Dispose()}}finally{$b.Dispose()}}
function Reg-Named([string]$sub,[string]$name){$b=[Microsoft.Win32.RegistryKey]::OpenBaseKey([Microsoft.Win32.RegistryHive]::CurrentUser,[Microsoft.Win32.RegistryView]::Registry64);try{$k=$b.OpenSubKey($sub);if(!$k){return $null};try{[string]$k.GetValue($name)}finally{$k.Dispose()}}finally{$b.Dispose()}}
function Link-Target([string]$path){if(!(Test-Path $path)){return $null};$w=New-Object -ComObject WScript.Shell;try{[string]$w.CreateShortcut($path).TargetPath}finally{[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($w)}}

if($env:GITHUB_ACTIONS-ne'true'-or$env:RUNNER_ENVIRONMENT-ne'github-hosted'-or$env:CI-ne'true'){throw 'This script runs only on a GitHub-hosted Actions runner.'}
if($ChildMode){
    if(!$WorkDirectory-or!$ParentSid-or!$BaselineFixture-or!$CandidateFixture){throw 'Child arguments missing.'}
    $identity=[Security.Principal.WindowsIdentity]::GetCurrent();$principal=[Security.Principal.WindowsPrincipal]::new($identity);$isAdmin=$principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
    if($isAdmin-or$identity.User.Value-eq$ParentSid){throw 'Child token is not an independent standard user.'}
    $manifest=Get-Content (Join-Path $WorkDirectory 'fixture-manifest.json') -Raw|ConvertFrom-Json
    foreach($f in @($manifest.Baseline,$manifest.Candidate)){if((Get-FileHash $f.Path -Algorithm SHA256).Hash-ne$f.SHA256){throw 'Fixture hash changed.'};if((Product-State $f.ProductCode)-ne-1){throw 'Fixture initially registered.'}}
    # Resolve the loaded child's profile, rather than inherited parent path variables.
    $local=[Environment]::GetFolderPath([Environment+SpecialFolder]::LocalApplicationData)
    $roaming=[Environment]::GetFolderPath([Environment+SpecialFolder]::ApplicationData)
    $env:USERPROFILE=[Environment]::GetFolderPath([Environment+SpecialFolder]::UserProfile)
    $env:LOCALAPPDATA=$local;$env:APPDATA=$roaming
    $env:TEMP=Join-Path $local 'Temp';$env:TMP=$env:TEMP
    [void][IO.Directory]::CreateDirectory($env:TEMP)
    $token=$manifest.Token;$productRoot=Join-Path $local "Programs\SC2CiRollbackQA$token";$oldDir=Join-Path $productRoot 'old';$appTarget=Join-Path $productRoot 'app';$menu=Join-Path $roaming "Microsoft\Windows\Start Menu\Programs\SC2 CI Rollback QA $token";$shortcut=Join-Path $menu "SC2 CI Rollback QA $token.lnk";$reg="Software\Microsoft\Windows\CurrentVersion\App Paths\SC2CiRollbackQA.$token.exe";$marker="Software\SC2CiRollbackQA\$token\Installer";$config=Join-Path $local "SC2CiRollbackQA\$token\config-canary.txt";$logs=Join-Path $WorkDirectory 'logs';[void][IO.Directory]::CreateDirectory($logs);[void][IO.Directory]::CreateDirectory((Split-Path $config));[IO.File]::WriteAllText($config,'ci-rollback-canary',[Text.UTF8Encoding]::new($false));$canaryHash=(Get-FileHash $config -Algorithm SHA256).Hash;$steps=[Collections.Generic.List[object]]::new();$cleanupSteps=[Collections.Generic.List[object]]::new();$failure=$null;$result=$null;$collisionHash=$null;$testPass=$false;$cleanupPass=$false
    try{
        [void](Run-Msi baseline-install @('/i',$BaselineFixture) @(0) $logs $steps);$oldHashes=File-Hashes $oldDir;if(@($oldHashes.Values|?{$null-ne$_}).Count-ne4){throw 'Baseline payload missing.'};$oldTarget=Join-Path $oldDir 'SC2Switcher.Wpf.exe';$before=[ordered]@{BaselineProductState=Product-State $manifest.Baseline.ProductCode;CandidateProductState=Product-State $manifest.Candidate.ProductCode;Hashes=$oldHashes;Shortcut=Link-Target $shortcut;AppPath=Reg-Default $reg;ApplicationMarker=Reg-Named $marker Application;StartMenuMarker=Reg-Named $marker StartMenu;Canary=(Get-FileHash $config).Hash};if($before.BaselineProductState-ne5-or$before.CandidateProductState-ne-1-or$before.Shortcut-ne$oldTarget-or$before.AppPath-ne$oldTarget-or$before.ApplicationMarker-ne'1'-or$before.StartMenuMarker-ne'1'-or$before.Canary-ne$canaryHash){throw 'Baseline state or entry-point proof failed.'}
        if(Test-Path $appTarget){throw 'Native collision target already exists.'};[IO.File]::WriteAllText($appTarget,'native-file-collision',[Text.UTF8Encoding]::new($false));$collisionHash=(Get-FileHash $appTarget).Hash
        $exit=Run-Msi native-upgrade @('/i',$CandidateFixture) @(1603) $logs $steps;$log=Join-Path $logs 'native-upgrade.log';$remove=@(Select-String $log -Pattern 'Action ended .*: RemoveExistingProducts\. Return value 1\.'|Select -First 1);$installFinalize=@(Select-String $log -Pattern 'Action ended .*: InstallFinalize\. Return value 3\.'|Where-Object{$remove-and$_.LineNumber-gt$remove.LineNumber}|Select -First 1);$copy=@(Select-String $log -Pattern 'Executing op: FileCopy\('|Where-Object{$remove-and$installFinalize-and$_.LineNumber-gt$remove.LineNumber-and$_.LineNumber-lt$installFinalize.LineNumber}|Select -First 1);$installFilesFailed=@(Select-String $log -Pattern 'Action ended .*: InstallFiles\. Return value 3\.'|Where-Object{$remove-and$_.LineNumber-gt$remove.LineNumber}|Select -First 1);$error5=@(Select-String $log -Pattern 'Note: 1: 140[1-4].* 3: 5\s*$')
        $after=[ordered]@{BaselineProductState=Product-State $manifest.Baseline.ProductCode;CandidateProductState=Product-State $manifest.Candidate.ProductCode;Hashes=File-Hashes $oldDir;Shortcut=Link-Target $shortcut;AppPath=Reg-Default $reg;ApplicationMarker=Reg-Named $marker Application;StartMenuMarker=Reg-Named $marker StartMenu;Canary=(Get-FileHash $config).Hash}
        $restored=$after.BaselineProductState-eq5-and$after.CandidateProductState-eq-1-and(($after.Hashes|ConvertTo-Json -Compress)-eq($oldHashes|ConvertTo-Json -Compress))-and$after.Shortcut-eq$before.Shortcut-and$after.AppPath-eq$before.AppPath-and$after.ApplicationMarker-eq$before.ApplicationMarker-and$after.StartMenuMarker-eq$before.StartMenuMarker-and$after.Canary-eq$canaryHash
        $testPass=$exit-eq1603-and[bool]$remove-and[bool]$copy-and[bool]$installFinalize-and$error5.Count-eq0-and$restored;$result=[ordered]@{Executed=$true;Pass=$testPass;Token=[ordered]@{Name=$identity.Name;SID=$identity.User.Value;ParentSID=$ParentSid;IsAdministrator=$isAdmin;DifferentSID=$identity.User.Value-ne$ParentSid};Expected1603=$exit-eq1603;RemoveExistingProductsSucceeded=[bool]$remove;RemoveExistingProductsLine=$(if($remove){$remove.LineNumber}else{$null});FileCopyBetweenRemovalAndFailure=[bool]$copy;FileCopyLine=$(if($copy){$copy.LineNumber}else{$null});InstallFilesFailed=[bool]$installFilesFailed;InstallFilesFailureLine=$(if($installFilesFailed){$installFilesFailed.LineNumber}else{$null});InstallFinalizeFailed=[bool]$installFinalize;InstallFinalizeFailureLine=$(if($installFinalize){$installFinalize.LineNumber}else{$null});MSIError5=$error5.Count;OldVersionRestored=$restored;Before=$before;After=$after;CollisionSHA256=$collisionHash;ConfigurationCanarySHA256=$canaryHash;Steps=$steps};if(!$testPass){$failure='Targeted rollback assertions failed.'}
    }catch{$failure=$_.Exception.ToString()}finally{
        foreach($f in @($manifest.Candidate,$manifest.Baseline)){try{[void](Run-Msi "cleanup-$($f.Role)" @('/x',$f.Path) @(0,1605) $logs $cleanupSteps)}catch{$failure="MSI cleanup failed for $($f.Role): $($_.Exception.Message). $failure"}}
        if(Test-Path $appTarget -PathType Leaf){$actualCollision=(Get-FileHash $appTarget -Algorithm SHA256).Hash;if(!$collisionHash-or$actualCollision-ne$collisionHash){$failure="Collision cleanup refused because bytes changed. $failure"}else{Remove-Item $appTarget -Force}};$canaryUnchanged=(Test-Path $config)-and(Get-FileHash $config -Algorithm SHA256).Hash-eq$canaryHash;if(Test-Path $config){Remove-Item $config -Force};$cleanupState=[ordered]@{BaselineProductState=Product-State $manifest.Baseline.ProductCode;CandidateProductState=Product-State $manifest.Candidate.ProductCode;CollisionAbsent=!(Test-Path $appTarget);CanaryUnchangedBeforeRemoval=$canaryUnchanged;CanaryRemoved=!(Test-Path $config);Steps=$cleanupSteps};$cleanupPass=$cleanupState.BaselineProductState-eq-1-and$cleanupState.CandidateProductState-eq-1-and$cleanupState.CollisionAbsent-and$cleanupState.CanaryUnchangedBeforeRemoval-and$cleanupState.CanaryRemoved;$cleanupState['Pass']=$cleanupPass;if(!$cleanupPass){$failure="Child cleanup invariants failed. $failure"};$report=[ordered]@{Completed=$true;Pass=($testPass-and$cleanupPass-and!$failure);Result=$result;Cleanup=$cleanupState;Failure=$failure;Steps=$steps};$report|ConvertTo-Json -Depth 10|Set-Content (Join-Path $WorkDirectory 'child-result.json') -Encoding utf8
    }
    if($failure-or!$testPass-or!$cleanupPass){exit 1};exit 0
}

$candidate=[IO.Path]::GetFullPath($CandidateMsi);if(!$candidate.StartsWith($artifactsRoot.TrimEnd('\')+'\',[StringComparison]::OrdinalIgnoreCase)-or!(Test-Path $candidate -PathType Leaf)){throw 'Candidate MSI must exist under this repository artifacts directory.'}
$adminIdentity=[Security.Principal.WindowsIdentity]::GetCurrent();$adminPrincipal=[Security.Principal.WindowsPrincipal]::new($adminIdentity);if(!$adminPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)){throw 'Parent process must be administrator on the disposable runner.'}
$runId=[guid]::NewGuid().ToString('N').Substring(0,12);if(!$OutputDirectory){$OutputDirectory=Join-Path $artifactsRoot "ci-installer-rollback\$($env:GITHUB_RUN_ID)"};$OutputDirectory=[IO.Path]::GetFullPath($OutputDirectory);if(!$OutputDirectory.StartsWith($artifactsRoot.TrimEnd('\')+'\',[StringComparison]::OrdinalIgnoreCase)-or(Test-Path $OutputDirectory)){throw 'Output directory must be a new path under repository artifacts.'};[void][IO.Directory]::CreateDirectory($OutputDirectory)
$runnerTemp=[IO.Path]::GetFullPath($env:RUNNER_TEMP);$work=Join-Path $runnerTemp "sc2-ci-rollback-$runId";$userName="sc2qa$($runId.Substring(0,8))";$user=$null;$userSid=$null;$passwordPlain=$null;$sourceHash=$null;$userRemoved=$false;$profileRemoved=$false;$workRemoved=$false;$parentCleanupErrors=[Collections.Generic.List[string]]::new()
try{
    [void][IO.Directory]::CreateDirectory($work);$sourceCopy=Join-Path $work 'source.msi';Copy-Item $candidate $sourceCopy;$sourceHash=(Get-FileHash $candidate).Hash;if((Get-FileHash $sourceCopy).Hash-ne$sourceHash){throw 'Source copy mismatch.'};$token=$runId.ToUpperInvariant();$basePath=Join-Path $work 'baseline.msi';$newPath=Join-Path $work 'candidate.msi';$base=New-Fixture $sourceCopy $basePath baseline '3.3.999' $token;$new=New-Fixture $sourceCopy $newPath candidate '3.4.0' $token;$base.SHA256=(Get-FileHash $basePath).Hash;$new.SHA256=(Get-FileHash $newPath).Hash;Verify-Fixture $base $token;Verify-Fixture $new $token
    $passwordPlain='A!a1'+[Convert]::ToBase64String([Security.Cryptography.RandomNumberGenerator]::GetBytes(36));$secure=ConvertTo-SecureString $passwordPlain -AsPlainText -Force;$user=New-LocalUser -Name $userName -Password $secure -PasswordNeverExpires -UserMayNotChangePassword -AccountNeverExpires;$userSid=$user.SID.Value;$usersGroup=Get-LocalGroup -SID 'S-1-5-32-545';Add-LocalGroupMember -Group $usersGroup.Name -Member $user -ErrorAction SilentlyContinue;$adminGroup=Get-LocalGroup -SID 'S-1-5-32-544';if((Get-LocalGroupMember -Group $adminGroup.Name -ErrorAction SilentlyContinue|Where-Object{$_.SID.Value-eq$userSid})){throw 'QA user unexpectedly belongs to Administrators.'};if(-not(Get-LocalGroupMember -Group $usersGroup.Name -ErrorAction SilentlyContinue|Where-Object{$_.SID.Value-eq$userSid})){throw 'QA user is not a member of the standard Users group.'}
    $manifest=[ordered]@{Token=$token;Source=[ordered]@{Path=$candidate;SHA256=$sourceHash};BaselineNature='Simulated lower-version copy of the same corrected candidate payload; not an original 3.3 upgrade claim.';Baseline=$base;Candidate=$new};$manifest|ConvertTo-Json -Depth 6|Set-Content (Join-Path $work 'fixture-manifest.json') -Encoding utf8;Copy-Item $PSCommandPath (Join-Path $work 'Test-CiRollback.ps1')
    & icacls.exe $work /inheritance:r /grant:r "$userName`:(OI)(CI)M" /grant:r 'SYSTEM:(OI)(CI)F' /grant:r 'Administrators:(OI)(CI)F'|Out-Null;if($LASTEXITCODE){throw 'Failed to assign dedicated work directory ACL.'}
    $credential=[Management.Automation.PSCredential]::new("$env:COMPUTERNAME\$userName",$secure);$stdout=Join-Path $work 'child.stdout.txt';$stderr=Join-Path $work 'child.stderr.txt';$pwsh=(Get-Process -Id $PID).Path;$quote={param([string]$value)'"'+$value.Replace('"','\"')+'"'};$childArguments=@('-NoProfile','-File',(& $quote (Join-Path $work 'Test-CiRollback.ps1')),'-ChildMode','-CandidateMsi',(& $quote $sourceCopy),'-WorkDirectory',(& $quote $work),'-ParentSid',$adminIdentity.User.Value,'-BaselineFixture',(& $quote $basePath),'-CandidateFixture',(& $quote $newPath));$process=Start-Process $pwsh -ArgumentList $childArguments -Credential $credential -LoadUserProfile -WorkingDirectory $work -WindowStyle Hidden -RedirectStandardOutput $stdout -RedirectStandardError $stderr -Wait -PassThru
    foreach($name in @('child-result.json','child.stdout.txt','child.stderr.txt','fixture-manifest.json','logs')){$p=Join-Path $work $name;if(Test-Path $p){Copy-Item $p $OutputDirectory -Recurse}}
    $sourceUnchanged=(Get-FileHash $candidate).Hash-eq$sourceHash;$summary=[ordered]@{Executed=$true;ChildExitCode=$process.ExitCode;Parent=[ordered]@{Name=$adminIdentity.Name;SID=$adminIdentity.User.Value;IsAdministrator=$true};TestUser=[ordered]@{Name=$userName;SID=$userSid;AdministratorGroup=$false};SourceSHA256=$sourceHash;SourceUnchanged=$sourceUnchanged;Result=$(if(Test-Path (Join-Path $work 'child-result.json')){Get-Content (Join-Path $work 'child-result.json') -Raw|ConvertFrom-Json}else{$null})};$summary|ConvertTo-Json -Depth 12|Set-Content (Join-Path $OutputDirectory 'result.json') -Encoding utf8
    if(!$sourceUnchanged-or$process.ExitCode-ne0-or$null-eq$summary.Result-or!$summary.Result.Pass-or!$summary.Result.Cleanup.Pass-or$null-eq$summary.Result.Result-or!$summary.Result.Result.Token.DifferentSID-or$summary.Result.Result.Token.IsAdministrator){throw 'Standard-user child did not complete with the required rollback, cleanup, token and source-integrity proof.'}
}finally{
    $passwordPlain=$null;try{if($user){Remove-LocalUser -Name $userName -ErrorAction SilentlyContinue;$userRemoved=$null-eq(Get-LocalUser -Name $userName -ErrorAction SilentlyContinue)}else{$userRemoved=$true}}catch{$parentCleanupErrors.Add("User cleanup: $($_.Exception.Message)")}
    try{if($userSid){$profile=Get-CimInstance Win32_UserProfile -Filter "SID='$userSid'" -ErrorAction SilentlyContinue;if($profile){$profilePath=[IO.Path]::GetFullPath($profile.LocalPath);$profilesRoot=[IO.Path]::GetFullPath((Join-Path $env:SystemDrive 'Users')).TrimEnd('\')+'\';if($profile.SID-ne$userSid-or$profilePath-eq[IO.Path]::GetFullPath($env:USERPROFILE)-or!$profilePath.StartsWith($profilesRoot,[StringComparison]::OrdinalIgnoreCase)){throw 'Refusing unexpected QA profile cleanup target.'};$profile|Remove-CimInstance -ErrorAction SilentlyContinue};$profileRemoved=$null-eq(Get-CimInstance Win32_UserProfile -Filter "SID='$userSid'" -ErrorAction SilentlyContinue)}else{$profileRemoved=$true}}catch{$parentCleanupErrors.Add("Profile cleanup: $($_.Exception.Message)")}
    try{if(Test-Path $work){$resolved=[IO.Path]::GetFullPath($work);$workItem=Get-Item $resolved -Force;if(!$resolved.StartsWith($runnerTemp.TrimEnd('\')+'\',[StringComparison]::OrdinalIgnoreCase)-or!(Split-Path $resolved -Leaf).StartsWith('sc2-ci-rollback-')-or($workItem.Attributes-band[IO.FileAttributes]::ReparsePoint)){throw 'Refusing unexpected CI work cleanup target.'};Remove-Item $resolved -Recurse -Force};$workRemoved=!(Test-Path $work)}catch{$parentCleanupErrors.Add("Work cleanup: $($_.Exception.Message)")}
    $sourceStillUnchanged=(Test-Path $candidate)-and$null-ne$sourceHash-and(Get-FileHash $candidate -Algorithm SHA256).Hash-eq$sourceHash;$parentCleanupPass=$userRemoved-and$profileRemoved-and$workRemoved-and$sourceStillUnchanged-and$parentCleanupErrors.Count-eq0;if(Test-Path $OutputDirectory){[ordered]@{Completed=$true;UserRemoved=$userRemoved;ProfileRemoved=$profileRemoved;WorkDirectoryRemoved=$workRemoved;SourceMsiOriginalUnchanged=$sourceStillUnchanged;Errors=$parentCleanupErrors;Pass=$parentCleanupPass}|ConvertTo-Json|Set-Content (Join-Path $OutputDirectory 'parent-cleanup.json') -Encoding utf8};if(!$parentCleanupPass){throw 'Parent cleanup or source integrity invariant failed; inspect parent-cleanup.json.'}
}
